#
# Copyright (C) RoyVortex, Sverdlovsk, 2025
#
name: Starlight
main: me.royvortex.starlight.StarlightPlugin
version: '${project.version}'
description: Advanced, light & modern all-in-one server management plugin.
author: RoyVortex
depend: [ nightcore ]
libraries:
  - org.apache.commons:commons-text:1.10.0
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - packetevents
  - DiscordSRV
api-version: 1.21